name: Billy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  aqua:
    name: Aqua scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull image
        run: docker pull nginx:latest

      - name: Manifest Generation
        env:
          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
          TRIVY_DB_REPOSITORY: registry.aquasec.com/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: registry.aquasec.com/trivy-java-db:1
          TRIVY_CHECKS_BUNDLE_REPOSITORY: registry.aquasec.com/trivy-checks:1

        run: |
          export BILLY_SERVER=https://billy.dev-aqua.codesec.aquasec.com
          
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          BINDIR="." sh install.sh
          ./billy generate \
            --access-token "${{ secrets.GITHUB_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --cspm-url https://stage.api.cloudsploit.com \
            --artifact-path "nginx:latest"
